# Generated by Django 4.2.5 on 2023-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equiposApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='fundacion',
            field=models.CharField(default='', max_length=25),
        ),
    ]
